apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: motorhub
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: shegxy69/motorhub-backend:v3.1
        resources:           # <--- ADD THIS
          requests:          # <--- ADD THIS
            cpu: "10m"       # <--- ADD THIS (Means 10 millicores of CPU)


---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: motorhub
spec:
  selector:
    app: backend
  ports:
  - port: 5000
    targetPort: 5000