apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: motorhub
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: shegxy69/motorhub-frontend:v1
        env:
        - name: BACKEND_URL
          value: "http://backend-service:5000"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: motorhub
spec:
  selector:
    app: frontend
  ports:
  - port: 8080
    targetPort: 8080