name: Build frontend

# 1. THE TRIGGER: 
on:
  push:
    branches: [ "main" ]
    paths: [ "frontend/**" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "frontend/**" ]

# 2. THE JOBS: 
jobs:
  build-and-push:
    # 3. THE SERVER: 
    runs-on: ubuntu-latest
    
    # 4. THE STEPS: The recipe the robot follows, one by one
    steps:
      # Step A: Download the code from your GitHub repository 
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step B: Log into your Docker Hub account using your hidden secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step C: Build the Dockerfile and push the image to Docker Hub
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./frontend                  # Where is the Dockerfile located?
      # Only push if the branch is exactly 'main'
          push: ${{ github.ref == 'refs/heads/main' }}    # Yes, upload it to Docker Hub
          tags: shegxy69/motorhub-frontend:v1  # What to name the image